version: "3.7"

services:
  zeppelin:
    image: apache/zeppelin:0.8.2
    ports:
      - 8080:8080
    volumes:
      - ~/.flashbot/zeppelin/logs:/logs
      - ~/.flashbot/zeppelin/notebook:/notebook
    environment:
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook

#  influxdb:
#    image: quay.io/influxdb/influxdb:2.0.0-alpha
#    ports:
#      - "9999:9999"
#    volumes:
#      - ~/.flashbot/data:/var/lib/flashbot/data
#    networks:
#      - mynet
#
#  chronograf:
#    image: quay.io/influxdb/chronograf:1.7.14
#    networks:
#      - mynet
#
#  kapacitor:
#    image: kapacitor
#    networks:
#      - mynet

#networks:
#  mynet:
#    ipam:
#      driver: default
#      config:
#        - subnet: 10.0.0.0/16

#volumes:
#  datavolume:
#    driver:
